name: Requirements Put Dynamo Items

on:
  workflow_call:
    inputs:
      dyn_pk:
        description: "primary key of table"
        required: true
        type: string
      dyn_sk:
        description: "sort key of table"
        required: false
        type: string
      dyn_items_path:
        description: "Path of JSON Items"
        required: true
        type: string

jobs:
  put-dyn:
    runs-on: ubuntu-latest
    env:
      repo-name: ${{ github.event.repository }}
    steps:
      - uses: actions/checkout@v3
      - name: Clone the pipeline repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.repo-name }}
          path: ${{ env.repo-name }}
      - name: Use Python3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          . venv/bin/activate
          source venv/bin/activate
      - name: validate file ${{ inputs.dyn_items_path }}
        env:
          PATH_ITEMS: ${{ inputs.dyn_items_path }}
          PRIM_KEY: ${{ inputs.dyn_pk }}
          SORT_KEY: ${{ inputs.dyn_sk }}
        run: |
          ls -R ${{ env.repo-name }}
          echo XXXXXXX
          ls -R src
          pwd
          source venv/bin/activate
          python3 ${{ env.repo-name }}/src/dynamo/put_table/validate_duplicates.py ${PATH_ITEMS} ${PRIM_KEY} ${SORT_KEY}
          echo success
